AllCops:
  RunRailsCops: true
  Include:
  - '**/Rakefile'
  - '**/config.ru'
  Exclude:
  - 'bin/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'node_modules/**/*'
  - 'spec/spec_helper.rb'
MethodLength:
  Max: 25
LineLength:
  Max: 270
HasAndBelongsToMany:
  Enabled: false
AbcSize:
  Enabled: false
DefaultScope:
  Enabled: false
Documentation:
  Enabled: false
