require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EncuentrosController do

  # This should return the minimal set of attributes required to create a valid
  # Encuentro. As you add validations to Encuentro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "estado" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EncuentrosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all encuentros as @encuentros" do
      encuentro = Encuentro.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:encuentros)).to eq([encuentro])
    end
  end

  describe "GET show" do
    it "assigns the requested encuentro as @encuentro" do
      encuentro = Encuentro.create! valid_attributes
      get :show, {:id => encuentro.to_param}, valid_session
      expect(assigns(:encuentro)).to eq(encuentro)
    end
  end

  describe "GET new" do
    it "assigns a new encuentro as @encuentro" do
      get :new, {}, valid_session
      expect(assigns(:encuentro)).to be_a_new(Encuentro)
    end
  end

  describe "GET edit" do
    it "assigns the requested encuentro as @encuentro" do
      encuentro = Encuentro.create! valid_attributes
      get :edit, {:id => encuentro.to_param}, valid_session
      expect(assigns(:encuentro)).to eq(encuentro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Encuentro" do
        expect {
          post :create, {:encuentro => valid_attributes}, valid_session
        }.to change(Encuentro, :count).by(1)
      end

      it "assigns a newly created encuentro as @encuentro" do
        post :create, {:encuentro => valid_attributes}, valid_session
        expect(assigns(:encuentro)).to be_a(Encuentro)
        expect(assigns(:encuentro)).to be_persisted
      end

      it "redirects to the created encuentro" do
        post :create, {:encuentro => valid_attributes}, valid_session
        expect(response).to redirect_to(Encuentro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved encuentro as @encuentro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Encuentro.any_instance.stub(:save).and_return(false)
        post :create, {:encuentro => { "estado" => "invalid value" }}, valid_session
        expect(assigns(:encuentro)).to be_a_new(Encuentro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Encuentro.any_instance.stub(:save).and_return(false)
        post :create, {:encuentro => { "estado" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested encuentro" do
        encuentro = Encuentro.create! valid_attributes
        # Assuming there are no other encuentros in the database, this
        # specifies that the Encuentro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Encuentro).to receive(:update).with({ "estado" => "MyString" })
        put :update, {:id => encuentro.to_param, :encuentro => { "estado" => "MyString" }}, valid_session
      end

      it "assigns the requested encuentro as @encuentro" do
        encuentro = Encuentro.create! valid_attributes
        put :update, {:id => encuentro.to_param, :encuentro => valid_attributes}, valid_session
        expect(assigns(:encuentro)).to eq(encuentro)
      end

      it "redirects to the encuentro" do
        encuentro = Encuentro.create! valid_attributes
        put :update, {:id => encuentro.to_param, :encuentro => valid_attributes}, valid_session
        expect(response).to redirect_to(encuentro)
      end
    end

    describe "with invalid params" do
      it "assigns the encuentro as @encuentro" do
        encuentro = Encuentro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Encuentro.any_instance.stub(:save).and_return(false)
        put :update, {:id => encuentro.to_param, :encuentro => { "estado" => "invalid value" }}, valid_session
        expect(assigns(:encuentro)).to eq(encuentro)
      end

      it "re-renders the 'edit' template" do
        encuentro = Encuentro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Encuentro.any_instance.stub(:save).and_return(false)
        put :update, {:id => encuentro.to_param, :encuentro => { "estado" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested encuentro" do
      encuentro = Encuentro.create! valid_attributes
      expect {
        delete :destroy, {:id => encuentro.to_param}, valid_session
      }.to change(Encuentro, :count).by(-1)
    end

    it "redirects to the encuentros list" do
      encuentro = Encuentro.create! valid_attributes
      delete :destroy, {:id => encuentro.to_param}, valid_session
      expect(response).to redirect_to(encuentros_url)
    end
  end

end
