require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JuegosController do

  # This should return the minimal set of attributes required to create a valid
  # Juego. As you add validations to Juego, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JuegosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all juegos as @juegos" do
      juego = Juego.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:juegos)).to eq([juego])
    end
  end

  describe "GET show" do
    it "assigns the requested juego as @juego" do
      juego = Juego.create! valid_attributes
      get :show, {:id => juego.to_param}, valid_session
      expect(assigns(:juego)).to eq(juego)
    end
  end

  describe "GET new" do
    it "assigns a new juego as @juego" do
      get :new, {}, valid_session
      expect(assigns(:juego)).to be_a_new(Juego)
    end
  end

  describe "GET edit" do
    it "assigns the requested juego as @juego" do
      juego = Juego.create! valid_attributes
      get :edit, {:id => juego.to_param}, valid_session
      expect(assigns(:juego)).to eq(juego)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Juego" do
        expect {
          post :create, {:juego => valid_attributes}, valid_session
        }.to change(Juego, :count).by(1)
      end

      it "assigns a newly created juego as @juego" do
        post :create, {:juego => valid_attributes}, valid_session
        expect(assigns(:juego)).to be_a(Juego)
        expect(assigns(:juego)).to be_persisted
      end

      it "redirects to the created juego" do
        post :create, {:juego => valid_attributes}, valid_session
        expect(response).to redirect_to(Juego.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved juego as @juego" do
        # Trigger the behavior that occurs when invalid params are submitted
        Juego.any_instance.stub(:save).and_return(false)
        post :create, {:juego => { "nombre" => "invalid value" }}, valid_session
        expect(assigns(:juego)).to be_a_new(Juego)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Juego.any_instance.stub(:save).and_return(false)
        post :create, {:juego => { "nombre" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested juego" do
        juego = Juego.create! valid_attributes
        # Assuming there are no other juegos in the database, this
        # specifies that the Juego created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Juego).to receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => juego.to_param, :juego => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested juego as @juego" do
        juego = Juego.create! valid_attributes
        put :update, {:id => juego.to_param, :juego => valid_attributes}, valid_session
        expect(assigns(:juego)).to eq(juego)
      end

      it "redirects to the juego" do
        juego = Juego.create! valid_attributes
        put :update, {:id => juego.to_param, :juego => valid_attributes}, valid_session
        expect(response).to redirect_to(juego)
      end
    end

    describe "with invalid params" do
      it "assigns the juego as @juego" do
        juego = Juego.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Juego.any_instance.stub(:save).and_return(false)
        put :update, {:id => juego.to_param, :juego => { "nombre" => "invalid value" }}, valid_session
        expect(assigns(:juego)).to eq(juego)
      end

      it "re-renders the 'edit' template" do
        juego = Juego.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Juego.any_instance.stub(:save).and_return(false)
        put :update, {:id => juego.to_param, :juego => { "nombre" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested juego" do
      juego = Juego.create! valid_attributes
      expect {
        delete :destroy, {:id => juego.to_param}, valid_session
      }.to change(Juego, :count).by(-1)
    end

    it "redirects to the juegos list" do
      juego = Juego.create! valid_attributes
      delete :destroy, {:id => juego.to_param}, valid_session
      expect(response).to redirect_to(juegos_url)
    end
  end

end
