require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrdensController do

  # This should return the minimal set of attributes required to create a valid
  # Orden. As you add validations to Orden, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "dni" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ordens as @ordens" do
      orden = Orden.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ordens)).to eq([orden])
    end
  end

  describe "GET show" do
    it "assigns the requested orden as @orden" do
      orden = Orden.create! valid_attributes
      get :show, {:id => orden.to_param}, valid_session
      expect(assigns(:orden)).to eq(orden)
    end
  end

  describe "GET new" do
    it "assigns a new orden as @orden" do
      get :new, {}, valid_session
      expect(assigns(:orden)).to be_a_new(Orden)
    end
  end

  describe "GET edit" do
    it "assigns the requested orden as @orden" do
      orden = Orden.create! valid_attributes
      get :edit, {:id => orden.to_param}, valid_session
      expect(assigns(:orden)).to eq(orden)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Orden" do
        expect {
          post :create, {:orden => valid_attributes}, valid_session
        }.to change(Orden, :count).by(1)
      end

      it "assigns a newly created orden as @orden" do
        post :create, {:orden => valid_attributes}, valid_session
        expect(assigns(:orden)).to be_a(Orden)
        expect(assigns(:orden)).to be_persisted
      end

      it "redirects to the created orden" do
        post :create, {:orden => valid_attributes}, valid_session
        expect(response).to redirect_to(Orden.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved orden as @orden" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orden.any_instance.stub(:save).and_return(false)
        post :create, {:orden => { "dni" => "invalid value" }}, valid_session
        expect(assigns(:orden)).to be_a_new(Orden)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orden.any_instance.stub(:save).and_return(false)
        post :create, {:orden => { "dni" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested orden" do
        orden = Orden.create! valid_attributes
        # Assuming there are no other ordens in the database, this
        # specifies that the Orden created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Orden).to receive(:update).with({ "dni" => "MyString" })
        put :update, {:id => orden.to_param, :orden => { "dni" => "MyString" }}, valid_session
      end

      it "assigns the requested orden as @orden" do
        orden = Orden.create! valid_attributes
        put :update, {:id => orden.to_param, :orden => valid_attributes}, valid_session
        expect(assigns(:orden)).to eq(orden)
      end

      it "redirects to the orden" do
        orden = Orden.create! valid_attributes
        put :update, {:id => orden.to_param, :orden => valid_attributes}, valid_session
        expect(response).to redirect_to(orden)
      end
    end

    describe "with invalid params" do
      it "assigns the orden as @orden" do
        orden = Orden.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orden.any_instance.stub(:save).and_return(false)
        put :update, {:id => orden.to_param, :orden => { "dni" => "invalid value" }}, valid_session
        expect(assigns(:orden)).to eq(orden)
      end

      it "re-renders the 'edit' template" do
        orden = Orden.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orden.any_instance.stub(:save).and_return(false)
        put :update, {:id => orden.to_param, :orden => { "dni" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested orden" do
      orden = Orden.create! valid_attributes
      expect {
        delete :destroy, {:id => orden.to_param}, valid_session
      }.to change(Orden, :count).by(-1)
    end

    it "redirects to the ordens list" do
      orden = Orden.create! valid_attributes
      delete :destroy, {:id => orden.to_param}, valid_session
      expect(response).to redirect_to(ordens_url)
    end
  end

end
