require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RondasController do

  # This should return the minimal set of attributes required to create a valid
  # Ronda. As you add validations to Ronda, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "numero" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RondasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rondas as @rondas" do
      ronda = Ronda.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rondas)).to eq([ronda])
    end
  end

  describe "GET show" do
    it "assigns the requested ronda as @ronda" do
      ronda = Ronda.create! valid_attributes
      get :show, {:id => ronda.to_param}, valid_session
      expect(assigns(:ronda)).to eq(ronda)
    end
  end

  describe "GET new" do
    it "assigns a new ronda as @ronda" do
      get :new, {}, valid_session
      expect(assigns(:ronda)).to be_a_new(Ronda)
    end
  end

  describe "GET edit" do
    it "assigns the requested ronda as @ronda" do
      ronda = Ronda.create! valid_attributes
      get :edit, {:id => ronda.to_param}, valid_session
      expect(assigns(:ronda)).to eq(ronda)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ronda" do
        expect {
          post :create, {:ronda => valid_attributes}, valid_session
        }.to change(Ronda, :count).by(1)
      end

      it "assigns a newly created ronda as @ronda" do
        post :create, {:ronda => valid_attributes}, valid_session
        expect(assigns(:ronda)).to be_a(Ronda)
        expect(assigns(:ronda)).to be_persisted
      end

      it "redirects to the created ronda" do
        post :create, {:ronda => valid_attributes}, valid_session
        expect(response).to redirect_to(Ronda.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ronda as @ronda" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ronda.any_instance.stub(:save).and_return(false)
        post :create, {:ronda => { "numero" => "invalid value" }}, valid_session
        expect(assigns(:ronda)).to be_a_new(Ronda)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ronda.any_instance.stub(:save).and_return(false)
        post :create, {:ronda => { "numero" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ronda" do
        ronda = Ronda.create! valid_attributes
        # Assuming there are no other rondas in the database, this
        # specifies that the Ronda created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Ronda).to receive(:update).with({ "numero" => "1" })
        put :update, {:id => ronda.to_param, :ronda => { "numero" => "1" }}, valid_session
      end

      it "assigns the requested ronda as @ronda" do
        ronda = Ronda.create! valid_attributes
        put :update, {:id => ronda.to_param, :ronda => valid_attributes}, valid_session
        expect(assigns(:ronda)).to eq(ronda)
      end

      it "redirects to the ronda" do
        ronda = Ronda.create! valid_attributes
        put :update, {:id => ronda.to_param, :ronda => valid_attributes}, valid_session
        expect(response).to redirect_to(ronda)
      end
    end

    describe "with invalid params" do
      it "assigns the ronda as @ronda" do
        ronda = Ronda.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ronda.any_instance.stub(:save).and_return(false)
        put :update, {:id => ronda.to_param, :ronda => { "numero" => "invalid value" }}, valid_session
        expect(assigns(:ronda)).to eq(ronda)
      end

      it "re-renders the 'edit' template" do
        ronda = Ronda.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ronda.any_instance.stub(:save).and_return(false)
        put :update, {:id => ronda.to_param, :ronda => { "numero" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ronda" do
      ronda = Ronda.create! valid_attributes
      expect {
        delete :destroy, {:id => ronda.to_param}, valid_session
      }.to change(Ronda, :count).by(-1)
    end

    it "redirects to the rondas list" do
      ronda = Ronda.create! valid_attributes
      delete :destroy, {:id => ronda.to_param}, valid_session
      expect(response).to redirect_to(rondas_url)
    end
  end

end
